name: Docker Run

on:
  push:
    branches:
      - master
      
jobs:
  pull-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Pull Docker Image
      run: docker pull tapasdocker01/javatestapp

    - name: Run Docker Container
      run: docker run -p 8080:8080 tapasdocker01/javatestapp
